common_flags := "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja"
common_flags_debug := common_flags + " -DCMAKE_BUILD_TYPE=Debug"
common_flags_release := common_flags + " -DCMAKE_BUILD_TYPE=Release"

CMAKE := "/usr/bin/cmake"

config:
  {{CMAKE}} -B build -S . {{common_flags_release}} -DENABLE_LSMTREE=ON

config-debug:
  {{CMAKE}} -B build -S . {{common_flags_debug}} -DENABLE_LSMTREE=ON

build:
  {{CMAKE}} --build build -j

import "scripts/lsmtree.just"
